name: build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4G'"
    steps:
    - name: Prepare Environment
      run: sudo apt-get update && curl -Lo kitware-archive.sh https://apt.kitware.com/kitware-archive.sh && sudo bash ./kitware-archive.sh
    - name: Install Dependencies
      run: sudo apt-get install ninja-build cmake
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt-hotspot
        java-version: 17
        cache: gradle
    - name: Build Normal Flavor
      run: bash ./gradlew assembleEmbedNoRecordRelease
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: outputs
        path: app/build/outputs/*
    - name: Artifact (Debug symbols)
      uses: actions/upload-artifact@v4
      with:
        name: love-android-unstripped-debugsyms
        path: app/build/intermediates/cxx
